FROM harbor.csde.caci.com/docker.io/library/debian:stable AS build-env

# hadolint ignore=DL3007
FROM gcr.io/distroless/base-debian12@sha256:937c7eaaf6f3f2d38a1f8c4aeff326f0c56e4593ea152e9e8f74d976dde52f56

#AWS GovCloud RDS cert
COPY bin/rds-ca-rsa4096-g1.pem /bin/rds-ca-rsa4096-g1.pem

COPY bin/milmove /bin/milmove

# Demo Environment certs
COPY config/tls/api.demo.dp3.us.chain.der.p7b /config/tls/api.demo.dp3.us.chain.der.p7b
COPY config/tls/api.demo.dp3.us.crt /config/tls/api.demo.dp3.us.crt

# Loadtesting Environment Certs
COPY config/tls/api.loadtest.dp3.us.chain.der.p7b /config/tls/api.loadtest.dp3.us.chain.der.p7b
COPY config/tls/api.loadtest.dp3.us.crt /config/tls/api.loadtest.dp3.us.crt

# Exp Environment Certs
COPY config/tls/api.exp.dp3.us.chain.der.p7b /config/tls/api.exp.dp3.us.chain.der.p7b
COPY config/tls/api.exp.dp3.us.crt /config/tls/api.exp.dp3.us.crt

COPY swagger/* /swagger/
COPY build /build
COPY public/static/react-file-viewer /public/static/react-file-viewer

# Mount mutable tmp for app packages like pdfcpu
# hadolint ignore=DL3007
VOLUME ["/tmp"]

ENTRYPOINT ["/bin/milmove"]

CMD ["serve", "--logging-level=debug"]

EXPOSE 8080