FROM harbor.csde.caci.com/docker.io/library/debian:stable AS build-env

# hadolint ignore=DL3007
FROM gcr.io/distroless/base-debian12@sha256:9c05cfd65f41c93a909ea67eb05b920a3b838780ea55df5421d48295d98ff957

#AWS GovCloud RDS cert
COPY bin/rds-ca-rsa4096-g1.pem /bin/rds-ca-rsa4096-g1.pem

COPY bin/milmove /bin/milmove

# Demo Environment certs
COPY config/tls/api.demo.dp3.us.chain.der.p7b /config/tls/api.demo.dp3.us.chain.der.p7b
COPY config/tls/api.demo.dp3.us.crt /config/tls/api.demo.dp3.us.crt

# Loadtesting Environment Certs
COPY config/tls/api.loadtest.dp3.us.chain.der.p7b /config/tls/api.loadtest.dp3.us.chain.der.p7b
COPY config/tls/api.loadtest.dp3.us.crt /config/tls/api.loadtest.dp3.us.crt

# Exp Environment Certs
COPY config/tls/api.exp.dp3.us.chain.der.p7b /config/tls/api.exp.dp3.us.chain.der.p7b
COPY config/tls/api.exp.dp3.us.crt /config/tls/api.exp.dp3.us.crt

COPY swagger/* /swagger/
COPY build /build
COPY public/static/react-file-viewer /public/static/react-file-viewer

# Mount mutable tmp for app packages like pdfcpu
# hadolint ignore=DL3007
VOLUME ["/tmp"]

ENTRYPOINT ["/bin/milmove"]

CMD ["serve", "--logging-level=debug"]

EXPOSE 8080